/**
 * Preference keys. Names mirror the documented UserDefaults keys so settings
 * remain easy to compare with the behaviour spec.
 */
export const UDKeys = {
  IS_GUEST: 'IS_GUEST',
  PREVIOUS_COUNT_MODE: 'PREVIOUS_COUNT_MODE',
  PREVIOUS_FOCUS_MODE: 'PREVIOUS_FOCUS_MODE',
  PREVIOUS_PLANT_MODE: 'PREVIOUS_PLANT_MODE',
  SELECTED_TAG_ID: 'SELECTED_TAG_ID',
  SELECTED_SPECIES_ID: 'SELECTED_SPECIES_ID',
  PREVIOUS_PLANT_TIME_MIN: 'PREVIOUS_PLANT_TIME_MIN',
  RINGTONE_MODE: 'RINGTONE_MODE',
  IS_SOUND_EFFECT_ENABLED: 'IS_SOUND_EFFECT_ENABLED',
  IS_SCREEN_ON: 'IS_SCREEN_ON',
  KILL_APP_KILL_TREE: 'KILL_APP_KILL_TREE',
  COUNTING_EXCEEDED_TIME: 'COUNTING_EXCEEDED_TIME',
  THREE_HOURS: 'THREE_HOURS',
  ARRANGE_BY_TIME: 'ARRANGE_BY_TIME',
  IS_MONDAY_FIRST: 'IS_MONDAY_FIRST',
  FIRST_WEEKDAY: 'FIRST_WEEKDAY',
  APP_SELECTED_LANGUAGE: 'APP_SELECTED_LANGUAGE',
  REQUIRE_TUTORIAL: 'REQUIRE_TUTORIAL',
  ONBOARDING_TOOLTIP_FIRST_TIME: 'ONBOARDING_TOOLTIP_FIRST_TIME',
  ONBOARDING_TOOLTIP_FIRST_TIME_FINISHED: 'ONBOARDING_TOOLTIP_FIRST_TIME_FINISHED',
  WALKTHROUGH_FINISHED: 'WALKTHROUGH_FINISHED',
  FOCUS_DURATION_LIMIT_FOR_FREE_USER: 'FOCUS_DURATION_LIMIT_FOR_FREE_USER',
  IS_PREMIUM_DEV: 'IS_PREMIUM_DEV',
  SELECTED_SPECIES_SORT_OPTION: 'SELECTED_SPECIES_SORT_OPTION',
  SELECTED_STORE_TREE_SORT_OPTION: 'SELECTED_STORE_TREE_SORT_OPTION',
  SELECTED_BG_MUSIC: 'SELECTED_BG_MUSIC',
  SHOW_ANIMATED_TREE: 'SHOW_ANIMATED_TREE',
  NOTIFICATIONS_ENABLED: 'NOTIFICATIONS_ENABLED',
  SOUND_VOLUME: 'SOUND_VOLUME',
  XMAS_THEME: 'XMAS_THEME',
  COIN_BALANCE: 'COIN_BALANCE',
  GEM_BALANCE: 'GEM_BALANCE',
  UNLOCKED_TREES: 'UNLOCKED_TREES',
  UNLOCKED_SOUNDS: 'UNLOCKED_SOUNDS',
  BOOST_USED_DATE: 'BOOST_USED_DATE',
  LAST_ACTIVE_AT: 'LAST_ACTIVE_AT',
} as const;

export type UDKey = (typeof UDKeys)[keyof typeof UDKeys];

export type CountModePref = 'DOWN' | 'UP';
export type FocusModePref = 'NORMAL' | 'DEEP';
export type PlantModePref = 'SINGLE' | 'TOGETHER';
export type RingtoneMode = 'normal' | 'vibrate' | 'silent' | 'system';
