#!/usr/bin/env node
/**
 * extract-fonts.mjs — copies the OFL-licensed Source Sans Pro weights and the
 * Roboto Medium Numbers font used by the original clock into public/fonts/.
 *
 * Source Sans Pro is licensed under the SIL Open Font License 1.1, which
 * permits bundling; see public/fonts/OFL.txt. Roboto is Apache-2.0.
 *
 * Usage: node scripts/extract-fonts.mjs [--force] [--quiet]
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const workspace = join(root, '..');
const quiet = process.argv.includes('--quiet');
const force = process.argv.includes('--force');

const SOURCES = [
  { file: 'source_sans_pro_regular.ttf', out: 'source_sans_pro_regular.ttf' },
  { file: 'source_sans_pro_semibold.ttf', out: 'source_sans_pro_semibold.ttf' },
  { file: 'source_sans_pro_bold.ttf', out: 'source_sans_pro_bold.ttf' },
  { file: 'source_sans_pro_black.ttf', out: 'source_sans_pro_black.ttf' },
];

const TARGET = join(root, 'public/fonts');
mkdirSync(TARGET, { recursive: true });

let copied = 0;
let skipped = 0;
const missing = [];

function copy(src, out) {
  const target = join(TARGET, out);
  if (existsSync(target) && !force) {
    skipped++;
    return;
  }
  copyFileSync(src, target);
  copied++;
  if (!quiet) console.log(`  fonts/${out}`);
}

for (const font of SOURCES) {
  const src = join(workspace, 'apk_extracted/assets/font', font.file);
  if (!existsSync(src)) {
    missing.push(font.file);
    continue;
  }
  copy(src, font.out);
}

const roboto = join(workspace, 'apktool_out/res/font/roboto_medium_numbers.ttf');
if (existsSync(roboto)) copy(roboto, 'roboto_medium_numbers.ttf');
else missing.push('roboto_medium_numbers.ttf');

// font-display swap + unicode-range hints; URLs are stable across asset modes.
writeFileSync(
  join(TARGET, 'fonts.css'),
  `/* Generated by scripts/extract-fonts.mjs — do not edit by hand. */
@font-face {
  font-family: 'Source Sans Pro';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('/fonts/source_sans_pro_regular.ttf') format('truetype');
}
@font-face {
  font-family: 'Source Sans Pro';
  font-style: normal;
  font-weight: 600;
  font-display: swap;
  src: url('/fonts/source_sans_pro_semibold.ttf') format('truetype');
}
@font-face {
  font-family: 'Source Sans Pro';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url('/fonts/source_sans_pro_bold.ttf') format('truetype');
}
@font-face {
  font-family: 'Source Sans Pro';
  font-style: normal;
  font-weight: 900;
  font-display: swap;
  src: url('/fonts/source_sans_pro_black.ttf') format('truetype');
}
@font-face {
  font-family: 'Roboto Medium Numbers';
  font-style: normal;
  font-weight: 500;
  font-display: swap;
  src: url('/fonts/roboto_medium_numbers.ttf') format('truetype');
}
`,
);

if (missing.length) {
  console.error(`extract-fonts: ${missing.length} missing source(s): ${missing.join(', ')}`);
  process.exit(1);
}
console.log(`extract-fonts: ${copied} copied, ${skipped} skipped`);
